### ISSUE TITLE
ffmpeg drawtext

### ISSUE THREAD

**Issue by takeruts** [OpenVisualCloud/Ad-Insertion-Sample#121]
I cannot make this project because it looks missing to define font file on ffmpeg drawtext in "ad-insertion/ad-segment/build.sh" 

bash into new container...ssai_ad_content_segment
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --extra-libs='-lpthread -lm' --enable-shared --enable-gpl --enable-libass --enable-libfreetype --disable-xlib --disable-sdl2 --enable-openssl --enable-nonfree --disable-vaapi --disable-hwaccels --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvthevc --enable-libsvtav1
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'archive/car6.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:05.06, start: 0.000000, bitrate: 5384 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/bt709), 1920x1080 [SAR 1:1 DAR 16:9], 5395 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[Parsed_drawtext_2 @ 0x56184c3ee640] No font filename provided
[AVFilterGraph @ 0x56184b46bac0] Error initializing filter 'drawtext' with args 'text=Server-Side AD Insertion:x=(w-text_w)/2:y=(h-text_h)/3:fontsize=100:fontcolor=white'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0

**Comment by takeruts** [comment]
Sorry,  it worked after installed ttf with command below.
$ sudo apt-get install ttf-mscorefonts-installer

**Comment by xwu2git** [comment]
If you can use the DejaVu font family, you can explicitly specify the fontfile with drawtext: fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf.
The DejaVu font family is already part of the docker image.
