### ISSUE TITLE
Build error in AWS

### ISSUE THREAD

**Issue by buyukkardes** [OpenVisualCloud/Ad-Insertion-Sample#198]
Hi,

With the latest Ad insertion code, I receive the following error during docker RUN useradd for any container;

useradd: Can't get unique UID (no more available UIDs)
useradd: can't create user
chown: invalid user: 'docker.docker'

I use AWS environment and I try to build with default ec2-user ( root user didn't work as well) with sudo make under build folder. I can see some progress if I replace build.sh $(id -u) with 1000 but this shouldn't be the way.

Any idea what can be the problem?

Thanks

**Comment by xwu2git** [comment]
What does $(id -u) say on AWS?

**Comment by xwu2git** [comment]
I think it gets down to $(id -u) and $(id -g). If they report correct uid and gid of the current user, then build should proceed.

**Comment by xwu2git** [comment]
I just did an AWS build. There is no issue compiling the sample.
Did you follow the steps in https://github.com/OpenVisualCloud/Ad-Insertion-Sample/wiki/Tutorial:-Running-AD-Insertion-on-Public-Cloud?
I used a 4GB memory sku. The nano sku (1GB) is insufficient.

**Comment by buyukkardes** [comment]
Hi,

Thanks for your comment. I did a clean check out and it looks like I found the issue. When used "make" I always received permission denied to /var/run/docker.sock, so I started the build with sudo make, however, sudo make return 0 for id -u. So, to resolve this, I used chmod 666 /var/run/docker.sock, then call make under build. It looks like it resolved the problem.

Thanks for your time.

**Comment by xwu2git** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html
Step 6: sudo usermod -a -G docker ec2-user
Then logout and re-login. You can then run any docker commands as a user.

**Comment by buyukkardes** [comment]
Thanks, it resolves the problem. We can close the ticket.
