### ISSUE TITLE
random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/.rnd

### ISSUE THREAD

**Issue by buyukkardes** [OpenVisualCloud/Ad-Insertion-Sample#200]
Hi All,

I use AWS EC2 environment. When I made a clean build (including newly pulled images and newly generated containers), below command works without any problem.

make start_docker_swarm

However, when I stopped EC2 instance and restart it, the above command gives the below error. As far as I see in internet, it is a user permission problem, but I don't understand why it worked first and not works after reboot the EC2. Any idea what can be the issue? Thanks

[ec2-user@ip-172-31-5-232 build]$ make start_docker_swarm
Deleted Containers:
1884af50c90153be0a529d730eb51e0037709603d71863a7621923bae2d372e1

Total reclaimed space: 111B
Deleted Volumes:
13ff124ce3f8d1e7961715d291caca3577d31e747e51774cf10988c4f45214e7

Total reclaimed space: 1.888GB
bash into new container...ssai_self_certificate
Can't load /home/.rnd into RNG
140471270625728:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/.rnd
Generating a RSA private key
....................................................................................++++
...............++++
writing new private key to '/home/self.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:Generating docker-compose.yml with PLATFORM=Xeon,FRAMEWORK=gst,NANALYTICS=1,NTRANSCODES=1,MINRESOLUTION=360p
failed to update secret adi_self_crt: Error response from daemon: rpc error: code = InvalidArgument desc = only updates to Labels are allowed
make[3]: *** [deployment/docker-swarm/CMakeFiles/start_docker_swarm] Error 1
make[2]: *** [deployment/docker-swarm/CMakeFiles/start_docker_swarm.dir/all] Error 2
make[1]: *** [deployment/docker-swarm/CMakeFiles/start_docker_swarm.dir/rule] Error 2
make: *** [start_docker_swarm] Error 2

**Comment by xwu2git** [comment]
Did you stop it before restarting? 
make stop_docker_swarm

**Comment by buyukkardes** [comment]
Thanks, it resolves, hence closing.
