### ISSUE TITLE
Build Issue 

### ISSUE THREAD

**Issue by mram0509** [OpenVisualCloud/Ad-Insertion-Sample#204]
I am getting the following error when I build:

"Sending build context to Docker daemon  8.704kB
Step 1/8 : FROM ubuntu:18.04
 ---> 72300a873c2c
Step 2/8 : RUN apt-get update && apt-get install -y openssh-server
 ---> Using cache
 ---> 8b8d5dc4134d
Step 3/8 : ARG  USER
 ---> Using cache
 ---> c6e952844008
Step 4/8 : ARG  GROUP
 ---> Using cache
 ---> a72350b2c39b
Step 5/8 : ARG  UID
 ---> Using cache
 ---> 494ff33054db
Step 6/8 : ARG  GID
 ---> Using cache
 ---> 438e3762397e
Step 7/8 : RUN  groupadd -f -g ${GID} ${GROUP};useradd -d /home -g ${GROUP} -K UID_MAX=${UID} -K UID_MIN=${UID} ${USER};chown -R ${USER}.${GROUP} /home
 ---> Running in 1bb403b82634
useradd: Can't get unique UID (no more available UIDs)
useradd: can't create user
chown: invalid user: 'docker.docker'
The command '/bin/sh -c groupadd -f -g ${GID} ${GROUP};useradd -d /home -g ${GROUP} -K UID_MAX=${UID} -K UID_MIN=${UID} ${USER};chown -R ${USER}.${GROUP} /home' returned a non-zero code: 1ned a non-zero code: 1
deployment/certificate/CMakeFiles/build_ssai_self_certificate.dir/build.make:57: recipe for target 'deployment/certificate/CMakeFiles/build_ssai_self_certificate' failedled
make[2]: *** [deployment/certificate/CMakeFiles/build_ssai_self_certificate] Error 1"

Is it due to docker setup. There is an instruction under Install Prerequisites:
Install docker engine. Make sure you setup docker to run as a regular user.  
How exactly should this be done?

**Comment by QuPengfei** [comment]
It is resolved in https://github.com/OpenVisualCloud/Ad-Insertion-Sample/issues/198

**Comment by mram0509** [comment]
I am trying to build this on prem and not on any CSP like AWS. What should I be doing to build it on a server on prem? Apologies for not including that info earlier.

**Comment by xwu2git** [comment]
No special step is needed. But please build it as a regular user and make sure your user can run with the docker permission. 
https://docs.docker.com/install/linux/linux-postinstall/

**Comment by mram0509** [comment]
I was able to build now. 
I have a one node k8s cluster. And have been trying to build and install on this one node cluster. 
When I do 
make volume - I get the following error.

'recipe for target 'deployment/kubernetes/CMakeFiles/volume' failed
make[3]: *** [deployment/kubernetes/CMakeFiles/volume] Error 127
CMakeFiles/Makefile2:352: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/all' failed
make[2]: *** [deployment/kubernetes/CMakeFiles/volume.dir/all] Error 2
CMakeFiles/Makefile2:359: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/rule' failed
make[1]: *** [deployment/kubernetes/CMakeFiles/volume.dir/rule] Error 2
Makefile:196: recipe for target 'volume' failed
make: *** [volume] Error 2
t@t:~/Ad-Insertion-Sample/build$ make volume
Making volumes...
here0
awk: line 18: syntax error at or near [
awk: line 19: syntax error at or near [
awk: line 23: syntax error at or near [
awk: line 25: syntax error at or near [
awk: line 28: syntax error at or near }
deployment/kubernetes/CMakeFiles/volume.dir/build.make:57: recipe for target 'deployment/kubernetes/CMakeFiles/volume' failed
make[3]: *** [deployment/kubernetes/CMakeFiles/volume] Error 2
CMakeFiles/Makefile2:352: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/all' failed
make[2]: *** [deployment/kubernetes/CMakeFiles/volume.dir/all] Error 2
CMakeFiles/Makefile2:359: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/rule' failed
make[1]: *** [deployment/kubernetes/CMakeFiles/volume.dir/rule] Error 2
Makefile:196: recipe for target 'volume' failed
make: *** [volume] Error 2'

Have you seen this error?

**Comment by xwu2git** [comment]
We did not anticipate this use case. Normally, POD cannot run on the master node.
Here is the workaround: 
(1) Untaint the master node for POD execution: kubectl taint nodes --all node-role.kubernetes.io/master-. This will make a single-node Kubernetes cluster.
(2) ssh-keygen and ssh-copy-id _hostname_ to enable passwordless access to your own host.
(3) Modify deployment/kubernetes/build.sh, line 22, hosts=( _hostname_ )
(4) make, make volume and make start_kubernetes

**Comment by mram0509** [comment]
This is still not working. Don’t know if there is a way to private message you

Trying this 😊

**Comment by xwu2git** [comment]
Which step is not working? What's the error message?

**Comment by mram0509** [comment]
It’s the same message

Making volumes...
awk: line 18: syntax error at or near [
awk: line 19: syntax error at or near [
awk: line 23: syntax error at or near [
awk: line 25: syntax error at or near [
awk: line 28: syntax error at or near }
deployment/kubernetes/CMakeFiles/volume.dir/build.make:57: recipe for target 'deployment/kubernetes/CMakeFiles/volume' failed
make[3]: *** [deployment/kubernetes/CMakeFiles/volume] Error 2
CMakeFiles/Makefile2:352: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/all' failed
make[2]: *** [deployment/kubernetes/CMakeFiles/volume.dir/all] Error 2
CMakeFiles/Makefile2:359: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/rule' failed
make[1]: *** [deployment/kubernetes/CMakeFiles/volume.dir/rule] Error 2
Makefile:196: recipe for target 'volume' failed
make: *** [volume] Error 2

Are you with Intel? I am. If you are – could you send me you email address, Then I cn asend you the IP address of my system.

Regards,
Mayura

**Comment by xwu2git** [comment]
Most likely, you forgot to run make after modifying the build script. 
You can email me at --xintian.wu_at_intel.com--

**Comment by xwu2git** [comment]
Resolved? Lack of gawk on the system.

**Comment by mram0509** [comment]
yes - resolved!
