### ISSUE TITLE
Some pods are always "pending" for PV is started on untainted master node

### ISSUE THREAD

**Issue by lvcarry** [OpenVisualCloud/Ad-Insertion-Sample#218]
Deploy ADI on kubernetes:

[root@av09-21-wp ~]# kubectl get pods --all-namespaces

NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE

default       ad-content-5fd4684bf7-w4n2w             0/1     Pending   0          47m

default       ad-decision-7bf64d94c9-g59l8            1/1     Running   0          47m

default       ad-insertion-6b6fc765c9-n8ss4           0/1     Pending   0          47m

default       ad-transcode-568594c89-8vm58            0/1     Pending   0          47m

default       content-provider-569c44fb7c-gptff       0/1     Pending   0          47m

default       content-transcode-56b8658d57-nmnb7      0/1     Pending   0          47m

 

All these pods need mount PV. The log info is shown:

[root@ar09-28-wp ~]# kubectl describe pods ad-content-877bb8cdc-g7ts5

Name:           ad-content-877bb8cdc-g7ts5

 Events:

  Type     Reason            Age               From               Message

  ----     ------            ----              ----               -------

  Warning  FailedScheduling  5s (x4 over 77s)  default-scheduler  **0/2 nodes are available: 1 node(s) didn't find available persistent volumes to bind, 1 node(s) had taints that the pod didn't tolerate.**

 The root cause is new ADI commit (https://github.com/OpenVisualCloud/Ad-Insertion-Sample/commit/4e79cd891f1aa805dee8f56d1d3d974bd13b8adb)
which will start PV on untainted master node, but master cannot be deployed pods.

Then error occurs.

**Comment by QuPengfei** [comment]
it is expected. it help on singl-node cluser

kubectl taint node master1 node-role.kubernetes.io/master:NoSchedule

**Comment by xwu2git** [comment]
Please test #219.

**Comment by xwu2git** [comment]
There is some confusion in the problem description.
The master node, by default, is tainted with node-role.kubernetes.io/master:NoSchedule. 
The script is supposed to not put PV on the master if master is tainted.
If you remove the taint (like those in a single-node cluster), then master becomes POD available. Thus the script can possibly put PV on it.

**Comment by xwu2git** [comment]
The original commit 4e79cd8 tries to enable single-node cluster. But it has a bug that all node properties are on a single line thus grep and cut does not work. Please test the fix #219.

**Comment by lvcarry** [comment]
With fix #219,I still failed to deploy ADI.
Pods are still “pending” with same error log:
Then I checked the pv:
[root@ar09-28-wp build]# kubectl describe pv ad-archive
Name:              ad-archive
Labels:            <none>
Annotations:       Finalizers:  [kubernetes.io/pv-protection]
StorageClass:      ad-archive
Status:            Available
Claim:
Reclaim Policy:    Retain
Access Modes:      ROX
VolumeMode:        Filesystem
Capacity:          1Gi
Node Affinity:
  Required Terms:
    Term 0:        **kubernetes.io/hostname in [master1]**


I also tried with the fixed cmd directly and it returns 2 nodes but master1 is the first one:

[root@ar09-28-wp build]# kubectl get node -l vcac-zone!=yes -o jsonpath='{range .items[*]}{"\n"}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}:{range @.spec.taints[*]}{@.key}={@.effect};{end}{end}' | grep : | grep Ready=True | grep -v NoSchedule | cut -f1 -d':'
**master1
node1**

I think only when the returned value is : node1, master1. Then host[0] can be node1 as we expected?

**Comment by xwu2git** [comment]
Why your master node is schedule-able?

**Comment by lvcarry** [comment]
Hi all,
 My master1 is No-schedule
 i tried this cmd again today and nothing will return.
 None "master1" , neither "node1".

**Comment by lvcarry** [comment]
this is master1 output:
root@ar09-28-wp:/usr/src/ad-insertion/build# kubectl get node -o yaml | grep taint -A 5
          f:taints: {}
      manager: kubectl
      operation: Update
      time: "2020-05-09T07:48:16Z"
    - apiVersion: v1
      fieldsType: FieldsV1
--
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  status:
    addresses:
    - address: 10.166.31.128

**Comment by xwu2git** [comment]
In your above, the bold text is from master1 or node1? What about the smaller font text? 
Could you show what's the output of **kubectl get node -l vcac-zone!=yes -o jsonpath='{range .items[]}{"\n"}{@.metadata.name}:{range @.status.conditions[]}{@.type}={@.status};{end}:{range @.spec.taints[*]}{@.key}={@.effect};{end}{end}'**

**Comment by lvcarry** [comment]
All above outputs are executed on master1 because "kubectl" cannot recognized in node1.
Output of suggested cmd is :
[root@ar09-28-wp ~]# kubectl get node -l vcac-zone!=yes -o jsonpath='{range .items[]}{"\n"}{@.metadata.name}:{range @.status.conditions[]}{@.type}={@.status};{end}:{range @.spec.taints[*]}{@.key}={@.effect};{end}{end}'

master1:NetworkUnavailable=False;:node-role.kubernetes.io/master=NoSchedule;

**Comment by xwu2git** [comment]
So master1 NoSchedule. grep -v NoSchedule will filter out master1. 
So the issue is not master1. It's filtered out as intended.
My question is: where is your node1? Why Kubernetes kubctl get node does not show node1?

**Comment by xwu2git** [comment]
Or is your node1 labeled as vcac-zone=yes, thus it's also filtered out?
Then in this case, there is nothing wrong:
Your master is not scheduleable and it does not make sense to let vcac-a do CPU-intensive work. Thus there is no suitable node to put the PV(s) on.

**Comment by lvcarry** [comment]
No, my node1 has no label "vcac-zone".
I copied all related logs and output here in attachment.

[adi_node_log.txt](https://github.com/OpenVisualCloud/Ad-Insertion-Sample/files/4613046/adi_node_log.txt)

**Comment by xwu2git** [comment]
I see the issue now. Some nodes don't have the spec.taints section. Somehow the jsonpath statement lists nodes only with some taint.

**Comment by xwu2git** [comment]
Could you try this: kubectl get node -l vcac-zone!=yes -o custom-columns=NAME:metadata.name,STATUS:status.conditions[-1].type,TAINT:spec.taints | grep " Ready " | grep -v "NoSchedule"

**Comment by lvcarry** [comment]
root@ar09-28-wp:~# kubectl get node -l vcac-zone!=yes -o custom-columns=NAME:metadata.name,STATUS:status.conditions[-1].type,TAINT:spec.taints | grep " Ready " | grep -v "NoSchedule"
node1     Ready    <none>

And output of "kubectl get node -o json" is attached here.
[nodes_json.txt](https://github.com/OpenVisualCloud/Ad-Insertion-Sample/files/4613529/nodes_json.txt)

**Comment by xwu2git** [comment]
great, please try #222 .

**Comment by lvcarry** [comment]
Still failed.
Pods failed to start with this error:

  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    <unknown>             default-scheduler  Successfully assigned default/ad-content-5fd4684bf7-vtd75 to node1
  Warning  FailedMount  114s (x11 over 8m6s)  kubelet, node1     MountVolume.NewMounter initialization failed for volume "ad-archive" : path "/tmp/archive/ad" does not exist
  Warning  FailedMount  96s (x3 over 6m3s)    kubelet, node1     Unable to attach or mount volumes: unmounted volumes=[ad-archive], unattached volumes=[ad-archive default-token-bvnx9]: timed out waiting for the condition

Cluster environment is ready and IP: root@10.166.31.128 (master1).
ADI is under : /usr/src/ad-insertion
Pls double check it.

**Comment by lvcarry** [comment]
Sorry for my mistake. It works now with following cmd one by one:
make update
make volume
make start_kubernetes 

Thanks for this quick fix.
