### ISSUE TITLE
build takes too long.

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Ad-Insertion-Sample#4]
Need to look at the docker dependencies and avoid any duplicated builds.

**Comment by dpatel257** [comment]
Explore possibility of make -j
As talked with Xintian, behaviour was seen similar. Parallel docker build does not work.
Docker storage driver does not handle multiple builds in parallel.

Two parts to this ticket:
- Slow local build. WIP for improvising docker caching by streamlining layers among different images
- Travis CI build. currently each component on travis is a separate job. Need to enable inter job caching

**Comment by xwu2git** [comment]
Completed by integrating with the latest docker image.
